HOST = "https://demoqa.com/"
TEXT_BOX_PAGE_LINK = f"{HOST}text-box"
RADIO_BUTTON_PAGE_LINK = f"{HOST}radio-button"
UPLOAD_DOWNLOAD_PAGE_LINK = f"{HOST}upload-download"
BROKEN_PAGE_LINK = f"{HOST}broken"
BOOKS_PAGE_LINK = f"{HOST}books"
LOGIN_PAGE_LINK = f"{HOST}login"
PROFILE_PAGE_LINK = f"{HOST}profile"
