HOST = "https://demoqa.com/"
TEXT_BOX_PAGE_LINK = f"{HOST}text-box"
RADIO_BUTTON_PAGE_LINK = f"{HOST}radio-button"
UPLOAD_DOWNLOAD_PAGE_LINK = f"{HOST}upload-download"
BROKEN_PAGE_LINK = f"{HOST}broken"
